### ISSUE TITLE
商品详情页处理，两张图片排列，有白色间隙

### ISSUE THREAD

**Issue by Hezhong123** [ifanrx/wxParser#8]
![21534218572_ pic](https://user-images.githubusercontent.com/16369674/44070866-c4844a34-9fb8-11e8-9cfa-d88cb6e8c63d.jpg)
商品页来处理，这样使用的使用的时候，有白边，不好操作

**Comment by yuxianwen** [comment]
公共样式加入

``` css
 .wxparser--wxParser-img {
  vertical-align: middle;
  width: 100%;
}
```
